include: package:effective_dart/analysis_options.1.3.0.yaml

linter:
    rules:
        # Flutter Lints
        avoid_print: true
        avoid_unnecessary_containers: true
        avoid_web_libraries_in_flutter: true
        no_logic_in_create_state: true
        sized_box_for_whitespace: true
        use_full_hex_values_for_flutter_colors: true

        # Effective Dart overrides
        avoid_dynamic_calls: true
        avoid_function_literals_in_foreach_calls: false
        curly_braces_in_flow_control_structures: false
        avoid_positional_boolean_parameters: false
        avoid_types_on_closure_parameters: false
        lines_longer_than_80_chars: false
        public_member_api_docs: false
        avoid_classes_with_only_static_members: false
