include: package:effective_dart/analysis_options.1.3.0.yaml

linter:
    rules:
        avoid_dynamic_calls: true
        avoid_function_literals_in_foreach_calls: false
        curly_braces_in_flow_control_structures: false
        avoid_types_on_closure_parameters: false
        lines_longer_than_80_chars: false
        public_member_api_docs: false
