name: bloc_extensions
description: Set of extensions for Bloc library
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  flutter_bloc: ^7.0.1

  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.1
