name: reloadable_bloc
description: An extension to the bloc state management library which automatically triggers state reloading
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.1

  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2

  effective_dart: ^1.3.1
